language: java

sudo: false
dist: trusty

cache:
 directories:
   - $HOME/.m2

before_install:
  - rm ~/.m2/settings.xml
  - export MAVEN_SKIP_RC=true
  - mvn -Xmx32M -v | grep 1.7.0; if [ $? = 0 ]; then export MAVEN_OPTS="-XX:MaxPermSize=240M"; else export MAVEN_OPTS="-XX:MaxMetaspaceSize=240M -XX:CompressedClassSpaceSize=240M"; fi
  - export MAVEN_OPTS="-Xmx512M $MAVEN_OPTS"

before_script:
  - unset GEM_PATH GEM_HOME IRBRC JRUBY_OPTS
  - export PATH="`pwd`/bin:$PATH"
  - echo $HOME

jdk:
  - oraclejdk8

os:
  - linux

env:
  global:
    - JAVA_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmn48M -Xmx512M"
    - MALLOC_ARENA_MAX=2
  matrix:
    - PHASE='-Ptest'
    - PHASE='-Prake -Dtask=test:jruby'
    - PHASE='-Prake -Dtask=test:jruby:fullint'
    - PHASE='-Prake -Dtask=test:jruby:jit'
    - PHASE='-Prake -Dtask=test:mri'
    - PHASE='-Prake -Dtask=test:mri:fullint'
    - PHASE='-Prake -Dtask=test:mri:jit'
    - PHASE='-Prake -Dtask=test:slow_suites'
    - PHASE='-Prake -Dtask=test:tracing'
    - PHASE='-Prake -Dtask=spec:ji'
    - PHASE='-Prake -Dtask=spec:compiler'
    - PHASE='-Prake -Dtask=spec:compiler' JRUBY_OPTS=-Xcompile.invokedynamic
    - PHASE='-Prake -Dtask=spec:ffi'
    - PHASE='-Prake -Dtask=spec:regression'
    - PHASE='-Prake -Dtask=spec:ruby:fast'
    - PHASE='-Prake -Dtask=spec:jruby'
    - PHASE='-Prake -Dtask=spec:jrubyc'
    - PHASE='-Prake -Dtask=spec:profiler'

install: tool/travis-install.sh
script: tool/travis-script.sh

notifications:
  irc:
    channels:
      - "irc.freenode.org#jruby"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true

  # update jruby-head installed on Travis CI
  webhooks:
    urls:
      - "https://rubies.travis-ci.org/rebuild/jruby-head"
# we are on a branch
    on_success: always
    on_failure: never

services:
  - redis-server
